flags: {}
packages:
- '.'
- location:
    git: git@github.com:rrnewton/pcg-random.git
    # Defend on a specific patch:
    commit: 52fe420d95f497e093b432db3287a334407956c6

extra-deps: []
resolver: lts-6.10
